id: A72CAFEB7
title: Wrathful Guru Mantra Visualization
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:48:06.156640
  last_modified_at: 2022-03-01 05:48:06.156643
