id: A72CAFEB7
title: 'The Verses that Saved Sakya from Sickness: A Prayer for Pacifying the Fear
  of Disease'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - it
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:48:06.155177
  last_modified_at: 2022-03-01 05:48:06.155180
