id: A72CAFEB7
title: Dhāraṇī of Goddess Parṇaśavarī
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:48:06.144275
  last_modified_at: 2022-03-01 05:48:06.144278
