id: A72CAFEB7
title: The Mantra Collection that Incinerates All the Diseases of this Kaliyuga
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:48:06.150222
  last_modified_at: 2022-03-01 05:48:06.150225
