id: A72CAFEB7
title: The Method to Pacify All Epidemics, Illnesses and Pandemics from the Sixty
  Solitary Forms of Yamāntaka
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:48:06.152269
  last_modified_at: 2022-03-01 05:48:06.152272
