id: A72CAFEB7
title: Daily Practice of Guru Rinpoche, Buddha of Medicine
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:48:06.142814
  last_modified_at: 2022-03-01 05:48:06.142817
