id: A72CAFEB7
title: Daily Practice of Dorje Gotrab
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:48:06.141687
  last_modified_at: 2022-03-01 05:48:06.141691
