id: A72CAFEB7
title: Sādhana of Bhaiṣajya Guru (Medicine Buddha)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:48:06.149293
  last_modified_at: 2022-03-01 05:48:06.149298
